language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t kuribohw/project234-backend
- docker push kuribohw/project234-backend
- docker pull dto80/project234-frontend:latest
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.20.0
  - secure: npKKU1SfDJbQdhGJMeB/NJfo6PEUJWx9FeE4lcSTja4vgK7lBr+oOSApLK7DWw/xqTRGDQYAkr7m8PAHaK4/llx9ebBsbbcZ1H1IpcA8fkc2E2n9vNuqHJivtpOJGukWILKxxjNeDBY3ORqQcd2hm/w/1rDXYZFLKfQB+P1k8dFQdVQkYCGjWqFSTnghATrxnBynY++cwTbjpKoia5Me5xvhOdpAomECr6W6zzZdtTSZ48J3rvVkI2ojMjpGkQkum+zJu6iFr1VDs4IAb6ExPRjtOGVFv39rrdwf3KRPVMz0rmNJSofPifhHGRdxXbtaXF8vQB/vCfwUp/s+UfgoRYUgIi+MMt9fpSyxfm1WE+nWRgAlR3ImlRstOmLosAozNwkHav5lJIQGKwxjGxbkOhr3Bjr9br8l2pYEbwwIPF+LgjfidR6b1R2XMdiOYi0h7/1BykWO4sKiIrs2P1MIde7hOrK6VA1NCMG8pAHJLSkV3rZvzsYulsUx2CVWgJxbMaqgzVZcmDYUrrEfCObSbrE+YT8wijhXR5/vz/SvTQZuUyn0RaXuf/tRQy783CsxerkD7qgetlpPJQCqp2EtQ7iT5sxcBm8z3e6CnS6jhjd2HzMkDrYZR2fkfQN6aTUrimL1yANGJkkCw+upDl/vo6vL2XlbtrZZ300iZx8Q330=
  - secure: dGqSBnPGLmGZrpxpki9kZKKS3m51QRHh24/sUNRa2Wd8FmXAp6YZLpMmqPZphZeCiVT9FUAk61U7uXOE5neW0cQIu3vyOEkkPsIkhopsLcskHlS6rMoFpQHqH1OuOB+LRgK03S09H1dMxnLhXStORFJf3gvGUQu1V11ZjiCMlfs7kS/Ec6O94p2fGqKGBS+8iv8EY/gUkBciIyOs2EqMIt9IvmeDEKVqLS5PZd5pi5u2ow5+vZGWer89AbvCy89uTfTK3tUBR+/bmFZxytIphMYSoS+4xTgZbSCEelGuOwHmcIpktRmFFqDXrNXsMYt4gwW/aDXMM5Ou3EJ/c+Z6hnHFg5j2AFKO7v78vlSE0obg+NELJlMohWrmczwkEmiYNkTT4Elw6r2jK7HQscMaQjh4PVU7/PfVsh9lCfhmjouh8dWAPLp6NnTIJvLHQW/9z/yzsPo3ul8B5hgS6MnTUkpfW/wAqzsWoVmcwTKahilM+bSDVKl4qZzGk7Z/oWS942NGm8T315TKmSkmKTVuRpPWo/8ZMDEHW1DPU9I7uA6PCYNhXVqE5CYrbvayYpRbvYGwgAyglqFl5qssStURKnJ+VF+EMCHVUvauiTi2E5lkosfkQzDp6MBbjndyVPNEQ20eWGVucfpRjhDaPD9i0PbPpnJXm0Qv8oZh7E2eyYI=
  - secure: GqH1s0CKWI7qu6JckVKTvdebzbRChLv3ypK1vB+D0xnK4Xr8JCSY4pvU4nYsoa4BLxvztx2FziXb0sayt0SI/GaLSGFXe2awHyrESCbUxFpSfbaRhd1PhsvbD0yE70M+W23ZBXDwN/JCl1Ak3gWORFevL/EwIp2em5tDSER83Y8SHBDLsAJZPv9HpxwTCfmRT4lf13XlMOnugkaaqcK50NVjEwDFUc2K9w/1IdGO3pDVWnKGE58v0lVUsu2/yv0xE0p16TLQ1T1fNWRl4hE0/gbFA+z6feuRTo08CCAUq56UrndD7FGHYrptu+YcK2V1coPlJ2dBr/rzR8cFC2xaacwSnvtZF8OONZyBzfzmLB4y6gdO21neBs9n/QVLdatRNz31q6LQ8TqcGdvrSZTpLpyqNwJG3dMducO/SVuHBQ2EwRHxlJJfYEquzFGaTuqPF27qa8/KGnstigobH0AWHTotA7UleZf7E+pIlzwggKut1Z9YB/GBtas25KE8z48vqIQOLg94Aob2PJXjcIZbN2OGoWhX+OHxgOQEn0ZMLM99LAS21LtgSYhhCMu6r/OmRYJ6Sst+MZBWRe9CTIcKCLPlhWArZthCrMHNczXvNJiSnIN5KivfLtStpJ85t1vNt/Vch/C+tzpKPF42u5qh++TTLz8kJBTOUji0toTG9/w=
