version: '3.3'
services:
  backend:
    image: kuribohw/project234-backend:latest
    ports: 
      - "8086:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8085:80"
    volumes:
      - type: bind
        source: ./keepjson
        target: /usr/share/nginx/html/assets

